# Generated by Django 5.0.4 on 2024-08-06 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('profile_picture_url', models.URLField()),
                ('page_url', models.URLField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('ig_username', models.CharField(max_length=200, null=True)),
                ('ig_followers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_archive_id', models.BigIntegerField(unique=True)),
                ('display_format', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel'), ('dco', 'DCO')], max_length=200)),
                ('link_url', models.URLField(null=True)),
                ('image', models.URLField(null=True)),
                ('video', models.URLField(null=True)),
                ('video_preview', models.URLField(null=True)),
                ('creation_time', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('body_html', models.TextField()),
                ('caption', models.CharField(max_length=200, null=True)),
                ('cta_text', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='facebook_ads.adcountry')),
                ('ad_creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='facebook_ads.facebookcreative')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='facebook_ads.facebookpage')),
            ],
        ),
    ]
