# Generated by Django 5.0.4 on 2024-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookad',
            name='cta_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
