# Generated by Django 5.0.4 on 2024-08-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0003_savedfacebookad'),
        ('sales_tracker', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookad',
            name='shopifyStore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_ads', to='sales_tracker.shopifystore'),
        ),
    ]
