# Generated by Django 5.0.4 on 2024-09-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0004_facebookad_shopifystore'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookad',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_ads', to='websites.website'),
        ),
    ]
