# Generated by Django 5.0.6 on 2024-09-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0005_facebookad_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookpage',
            old_name='page_id',
            new_name='facebook_page_id',
        ),
    ]
