# Generated by Django 5.0.6 on 2024-09-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0006_rename_page_id_facebookpage_facebook_page_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookpage',
            old_name='facebook_page_id',
            new_name='page_id',
        ),
        migrations.AlterField(
            model_name='facebookpage',
            name='profile_picture_url',
            field=models.TextField(),
        ),
    ]
