# Generated by Django 5.0.6 on 2024-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0007_rename_facebook_page_id_facebookpage_page_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookad',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='facebookad',
            name='video',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='facebookad',
            name='video_preview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='facebookpage',
            name='page_url',
            field=models.TextField(null=True),
        ),
    ]
