# Generated by Django 5.0.4 on 2024-08-20 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('hostname', models.CharField(max_length=200)),
                ('themedata', models.JSONField()),
                ('shopify_url', models.CharField(max_length=200)),
                ('locale', models.CharField(max_length=200)),
                ('currency', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('hostname', models.CharField(max_length=200)),
                ('themedata', models.JSONField()),
                ('shopify_url', models.CharField(max_length=200)),
                ('locale', models.CharField(max_length=200)),
                ('currency', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track_data', to='sales_tracker.store')),
            ],
        ),
        migrations.CreateModel(
            name='UserShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stores', to='sales_tracker.shopifystore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrackedStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_stores', to='sales_tracker.shopifystore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
