# Generated by Django 5.0.4 on 2024-07-09 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track_data', to='sales_tracker.store')),
            ],
        ),
    ]
