# Generated by Django 5.0.4 on 2024-08-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifystore',
            name='hostname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
