# Generated by Django 5.0.6 on 2024-06-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='google_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture_url',
            field=models.URLField(null=True),
        ),
    ]
