# Generated by Django 5.0.6 on 2024-06-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_google_id_alter_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='google_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
