name: SSH Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    types:
      - closed
    branches:
      - dev
      - main
jobs:
  ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install sshpass -y
      - run: sshpass -p 'Hlb98TE1Nf9B4viUw7' ssh -o StrictHostKeyChecking=no root@copiwin.com
      - run: cd /data/winning-product-api/
      - run: git pull
      - run: systemctl restart copiwinapi
